//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tasks.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskLock
    {
        public int Id { get; set; }
        public int TaskId { get; set; }
        public System.DateTime LockDate { get; set; }
        public long OwnerId { get; set; }
    
        public virtual Task Task { get; set; }
    }
}
